
import Classes.JobManager;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Group 2
 */
public class GenomeCompInputs extends javax.swing.JDialog {

    String ReffilePath;
    String deltafilePath;
    String deltafilename;

    GroupPFrame Gf = new GroupPFrame();
    public static BufferedImage originalImage;
    public static URL url;
    public static String jobIdGC;
    public static String submissionDateGC;
    public static String jobIdMP;
    public static String submissionDateMP;
    public static String submitdfurl;
    public static String submitmpurl;
    public static String downloadmpurl;

    /**
     * Creates new form GenomeComp
     */
    public GenomeCompInputs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Genome Comparison");
        MinIdentity.setText("95");
        MinLength.setText("2000");

//        if (GroupPFrame.nucmerran) {
//            continueButton.setEnabled(true);
//        } else {
//            continueButton.setEnabled(false);
//        }
        ButtonGroup buttonGroup = new ButtonGroup(); // create a button group , buttons in a button group knows how to behave together 
        buttonGroup.add(generateButton);
        buttonGroup.add(continueButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        generateButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeltaTextField = new javax.swing.JTextField();
        OpenDeltaFile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        continueButton = new javax.swing.JRadioButton();
        MinIdentity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MinLength = new javax.swing.JTextField();
        RunGenomeComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Option 1"));

        generateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateButton.setSelected(true);
        generateButton.setText("Generate genome comparison plot using a delta file");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("A .delta file stores the results of a pairwise alignment of two genomic sequences.");

        jLabel7.setText("It can be generated by executing the nucmer command which takes two DNA sequences as inputs:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("nucmer [options] <reference_file> <query_file>");

        jLabel3.setText("Delta file:");

        DeltaTextField.setEditable(false);

        OpenDeltaFile.setText("Open");
        OpenDeltaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenDeltaFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeltaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OpenDeltaFile))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(generateButton)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeltaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpenDeltaFile)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Option 2"));

        continueButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        continueButton.setText("Continue analysis from reference file");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(continueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(continueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MinIdentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinIdentityActionPerformed(evt);
            }
        });

        jLabel1.setText("Min Identity:");

        jLabel2.setText("Min Length:");

        RunGenomeComp.setText("Run");
        RunGenomeComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunGenomeCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinLength, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RunGenomeComp)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(MinIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(RunGenomeComp))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunGenomeCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunGenomeCompActionPerformed
        String minidentity = null;
        String minlength = null;

        // Min Identity
        if (MinIdentity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a value for min identity.");
        } else {
            minidentity = MinIdentity.getText();
        }

        //Min Length
        if (MinLength.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a value for min length.");
        } else {
            minlength = MinLength.getText();
        }

        if (generateButton.isSelected()) {
            //(filePath1 as the Query) and ReffilePath
            // 1) Upload the files to server
            // 2) Submit the job to server
            //Parameters for job submission
            submitdfurl = ServerConfigurationInputs.serverURL
                    + "/delta_filter/"
                    + minidentity + "/"
                    + minlength + "/"
                    + deltafilename + "/"
                    + deltafilename.substring(0, deltafilename.length() - 6) + ".fdelta";

            submitmpurl = ServerConfigurationInputs.serverURL
                    + "/mummerplot_general/"
                    + deltafilename.substring(0, deltafilename.length() - 6) + "/"
                    + deltafilename.substring(0, deltafilename.length() - 6) + ".fdelta";

            downloadmpurl = ServerConfigurationInputs.serverURL
                    + "/download/"
                    + deltafilename.substring(0, deltafilename.length() - 6) + ".png";

            System.out.println(submitdfurl);
            System.out.println(submitmpurl);
            System.out.println(downloadmpurl);

        } else {
//            submitdfurl = ServerConfigurationInputs.serverURL
//                    + "/delta_filter/"
//                    + minidentity + "/"
//                    + minlength + "/"
//                    + GroupPFrame.reffilename2 + ".delta/"
//                    + GroupPFrame.reffilename2 + ".fdelta";
//
//            submitmpurl = ServerConfigurationInputs.serverURL
//                    + "/mummerplot_general/"
//                    + GroupPFrame.reffilename2 + "/"
//                    + GroupPFrame.reffilename2 + ".fdelta";

            submitdfurl = ServerConfigurationInputs.serverURL
                    + "/delta_filter/"
                    + minidentity + "/"
                    + minlength + "/"
                    + "nucmer_output.delta/"
                    + "nucmer_output.fdelta";

            submitmpurl = ServerConfigurationInputs.serverURL
                    + "/mummerplot_general/"
                    + "nucmer_output/"
                    + "nucmer_output.fdelta";

            downloadmpurl = ServerConfigurationInputs.serverURL
                    + "/download/"
                    + "nucmer_output.png";

            System.out.println(submitdfurl);
            System.out.println(submitmpurl);
            System.out.println(downloadmpurl);

        }

        this.dispose();

        System.out.println("RUNNING");
    }//GEN-LAST:event_RunGenomeCompActionPerformed

    private void MinIdentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinIdentityActionPerformed

    }//GEN-LAST:event_MinIdentityActionPerformed

    private void OpenDeltaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenDeltaFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Delta File", "delta");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showDialog(jPanel1, "Open");

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            // save file path into a variable
            deltafilePath = selectedFile.getPath();
            deltafilename = selectedFile.getName();
            DeltaTextField.setText(selectedFile.getName());
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("File already exists.");
        }
    }//GEN-LAST:event_OpenDeltaFileActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        DeltaTextField.setEnabled(true);// activate the text field
        OpenDeltaFile.setEnabled(true); // activate the button

        if (continueButton.isSelected()) {

            DeltaTextField.setEnabled(false);// activate the text field
            OpenDeltaFile.setEnabled(false); // activate the button
        } else {
            DeltaTextField.setEnabled(true);// activate the text field
            OpenDeltaFile.setEnabled(true); // activate the button
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        DeltaTextField.setEnabled(false);// activate the text field
        OpenDeltaFile.setEnabled(false); // activate the button

        if (generateButton.isSelected()) {

            DeltaTextField.setEnabled(true);// activate the text field
            OpenDeltaFile.setEnabled(true); // activate the button
        } else {
            DeltaTextField.setEnabled(false);// activate the text field
            OpenDeltaFile.setEnabled(false); // activate the button
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    public URL returnurl() {
        return url;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenomeCompInputs.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenomeCompInputs.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenomeCompInputs.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenomeCompInputs.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GenomeCompInputs dialog = new GenomeCompInputs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeltaTextField;
    private javax.swing.JTextField MinIdentity;
    private javax.swing.JTextField MinLength;
    private javax.swing.JButton OpenDeltaFile;
    private javax.swing.JButton RunGenomeComp;
    private javax.swing.JRadioButton continueButton;
    private javax.swing.JRadioButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
